/*
 * Map entity
 */
var utility = require('./Tools')
, moment = require('moment')
, moment_tz = require('moment-timezone');

exports.Map = Map();

exports.mapRead = function (byteIni, byteLen, data) {

	var RSVD = 65534;
	var LOCK = 65535;
	var m = Map();
	var x = byteIni;

	for (var l=0; l<m.levels.length; l++) {
	    
		for (var s=0; s<m.levels[l].stalls.length; s++) {
		    
			m.levels[l].stalls[s].status = utility.BytesToInt(data[x], data[x+1]);
			var date = utility.getPlcDate(utility.BytesToInt(data[x+2], data[x+3]));
			m.levels[l].stalls[s].date = moment(date).format('YYYY-MM-DD');
			var time = utility.getPlcTime(utility.BytesToLong(data[x+4], data[x+5], data[x+6], data[x+7]));
			m.levels[l].stalls[s].time = moment(time).format('HH:mm:ss');
			
			switch(m.levels[l].stalls[s].status) {
				case 0 :
					m.free += 1;
					break;
				case LOCK :
					m.lock += 1;
					break;
				default :
					m.busy += 1;
					break;
			}
			x += 8;
		}		
	}
	return m;
}

exports.mapSize = function (byteIni, byteLen, data) {

	var RSVD = 65534;
	var LOCK = 65535;
	var m = Map();
	var x = byteIni;

	for (var l=0; l<m.levels.length; l++) {
    
		for (var s=0; s<m.levels[l].stalls.length; s++) {
		    
			m.levels[l].stalls[s].status = utility.BytesToInt(data[x], data[x+1]);
			x += 2;
		}		
	}
	return m;
}

function Map () {
    
    //this.data = {
	//var data = {
	return {
	    map: 'System Map',
	    spaces: 912,
		free: 0,
		busy: 0,
		lock: 0,
	    levels: [
		// basement B2
		{
		    nr: 1,
		    label: 'Basement B2',
		    min: 1,
		    max: 152,
		    stalls: [
				{ nr: 1, status: 0, date: '', time: '' },
				{ nr: 2, status: 0, date: '', time: '' },
				{ nr: 3, status: 0, date: '', time: '' },
				{ nr: 4, status: 0, date: '', time: '' },
				{ nr: 5, status: 0, date: '', time: '' },
				{ nr: 6, status: 0, date: '', time: '' },
				{ nr: 7, status: 0, date: '', time: '' },
				{ nr: 8, status: 0, date: '', time: '' },
				{ nr: 9, status: 0, date: '', time: '' },
				{ nr: 10, status: 0, date: '', time: '' },
				{ nr: 11, status: 0, date: '', time: '' },
				{ nr: 12, status: 0, date: '', time: '' },
				{ nr: 13, status: 0, date: '', time: '' },
				{ nr: 14, status: 0, date: '', time: '' },
				{ nr: 15, status: 0, date: '', time: '' },
				{ nr: 16, status: 0, date: '', time: '' },
				{ nr: 17, status: 0, date: '', time: '' },
				{ nr: 18, status: 0, date: '', time: '' },
				{ nr: 19, status: 0, date: '', time: '' },
				{ nr: 20, status: 0, date: '', time: '' },
				{ nr: 21, status: 0, date: '', time: '' },
				{ nr: 22, status: 0, date: '', time: '' },
				{ nr: 23, status: 0, date: '', time: '' },
				{ nr: 24, status: 0, date: '', time: '' },
				{ nr: 25, status: 0, date: '', time: '' },
				{ nr: 26, status: 0, date: '', time: '' },
				{ nr: 27, status: 0, date: '', time: '' },
				{ nr: 28, status: 0, date: '', time: '' },
				{ nr: 29, status: 0, date: '', time: '' },
				{ nr: 30, status: 0, date: '', time: '' },
				{ nr: 31, status: 0, date: '', time: '' },
				{ nr: 32, status: 0, date: '', time: '' },
				{ nr: 33, status: 0, date: '', time: '' },
				{ nr: 34, status: 0, date: '', time: '' },
				{ nr: 35, status: 0, date: '', time: '' },
				{ nr: 36, status: 0, date: '', time: '' },
				{ nr: 37, status: 0, date: '', time: '' },
				{ nr: 38, status: 0, date: '', time: '' },
				{ nr: 39, status: 0, date: '', time: '' },
				{ nr: 40, status: 0, date: '', time: '' },
				{ nr: 41, status: 0, date: '', time: '' },
				{ nr: 42, status: 0, date: '', time: '' },
				{ nr: 43, status: 0, date: '', time: '' },
				{ nr: 44, status: 0, date: '', time: '' },
				{ nr: 45, status: 0, date: '', time: '' },
				{ nr: 46, status: 0, date: '', time: '' },
				{ nr: 47, status: 0, date: '', time: '' },
				{ nr: 48, status: 0, date: '', time: '' },
				{ nr: 49, status: 0, date: '', time: '' },
				{ nr: 50, status: 0, date: '', time: '' },
				{ nr: 51, status: 0, date: '', time: '' },
				{ nr: 52, status: 0, date: '', time: '' },
				{ nr: 53, status: 0, date: '', time: '' },
				{ nr: 54, status: 0, date: '', time: '' },
				{ nr: 55, status: 0, date: '', time: '' },
				{ nr: 56, status: 0, date: '', time: '' },
				{ nr: 57, status: 0, date: '', time: '' },
				{ nr: 58, status: 0, date: '', time: '' },
				{ nr: 59, status: 0, date: '', time: '' },
				{ nr: 60, status: 0, date: '', time: '' },
				{ nr: 61, status: 0, date: '', time: '' },
				{ nr: 62, status: 0, date: '', time: '' },
				{ nr: 63, status: 0, date: '', time: '' },
				{ nr: 64, status: 0, date: '', time: '' },
				{ nr: 65, status: 0, date: '', time: '' },
				{ nr: 66, status: 0, date: '', time: '' },
				{ nr: 67, status: 0, date: '', time: '' },
				{ nr: 68, status: 0, date: '', time: '' },
				{ nr: 69, status: 0, date: '', time: '' },
				{ nr: 70, status: 0, date: '', time: '' },
				{ nr: 71, status: 0, date: '', time: '' },
				{ nr: 72, status: 0, date: '', time: '' },
				{ nr: 73, status: 0, date: '', time: '' },
				{ nr: 74, status: 0, date: '', time: '' },
				{ nr: 75, status: 0, date: '', time: '' },
				{ nr: 76, status: 0, date: '', time: '' },
				{ nr: 77, status: 0, date: '', time: '' },
				{ nr: 78, status: 0, date: '', time: '' },
				{ nr: 79, status: 0, date: '', time: '' },
				{ nr: 80, status: 0, date: '', time: '' },
				{ nr: 81, status: 0, date: '', time: '' },
				{ nr: 82, status: 0, date: '', time: '' },
				{ nr: 83, status: 0, date: '', time: '' },
				{ nr: 84, status: 0, date: '', time: '' },
				{ nr: 85, status: 0, date: '', time: '' },
				{ nr: 86, status: 0, date: '', time: '' },
				{ nr: 87, status: 0, date: '', time: '' },
				{ nr: 88, status: 0, date: '', time: '' },
				{ nr: 89, status: 0, date: '', time: '' },
				{ nr: 90, status: 0, date: '', time: '' },
				{ nr: 91, status: 0, date: '', time: '' },
				{ nr: 92, status: 0, date: '', time: '' },
				{ nr: 93, status: 0, date: '', time: '' },
				{ nr: 94, status: 0, date: '', time: '' },
				{ nr: 95, status: 0, date: '', time: '' },
				{ nr: 96, status: 0, date: '', time: '' },
				{ nr: 97, status: 0, date: '', time: '' },
				{ nr: 98, status: 0, date: '', time: '' },
				{ nr: 99, status: 0, date: '', time: '' },
				{ nr: 100, status: 0, date: '', time: '' },
				{ nr: 101, status: 0, date: '', time: '' },
				{ nr: 102, status: 0, date: '', time: '' },
				{ nr: 103, status: 0, date: '', time: '' },
				{ nr: 104, status: 0, date: '', time: '' },
				{ nr: 105, status: 0, date: '', time: '' },
				{ nr: 106, status: 0, date: '', time: '' },
				{ nr: 107, status: 0, date: '', time: '' },
				{ nr: 108, status: 0, date: '', time: '' },
				{ nr: 109, status: 0, date: '', time: '' },
				{ nr: 110, status: 0, date: '', time: '' },
				{ nr: 111, status: 0, date: '', time: '' },
				{ nr: 112, status: 0, date: '', time: '' },
				{ nr: 113, status: 0, date: '', time: '' },
				{ nr: 114, status: 0, date: '', time: '' },
				{ nr: 115, status: 0, date: '', time: '' },
				{ nr: 116, status: 0, date: '', time: '' },
				{ nr: 117, status: 0, date: '', time: '' },
				{ nr: 118, status: 0, date: '', time: '' },
				{ nr: 119, status: 0, date: '', time: '' },
				{ nr: 120, status: 0, date: '', time: '' },
				{ nr: 121, status: 0, date: '', time: '' },
				{ nr: 122, status: 0, date: '', time: '' },
				{ nr: 123, status: 0, date: '', time: '' },
				{ nr: 124, status: 0, date: '', time: '' },
				{ nr: 125, status: 0, date: '', time: '' },
				{ nr: 126, status: 0, date: '', time: '' },
				{ nr: 127, status: 0, date: '', time: '' },
				{ nr: 128, status: 0, date: '', time: '' },
				{ nr: 129, status: 0, date: '', time: '' },
				{ nr: 130, status: 0, date: '', time: '' },
				{ nr: 131, status: 0, date: '', time: '' },
				{ nr: 132, status: 0, date: '', time: '' },
				{ nr: 133, status: 0, date: '', time: '' },
				{ nr: 134, status: 0, date: '', time: '' },
				{ nr: 135, status: 0, date: '', time: '' },
				{ nr: 136, status: 0, date: '', time: '' },
				{ nr: 137, status: 0, date: '', time: '' },
				{ nr: 138, status: 0, date: '', time: '' },
				{ nr: 139, status: 0, date: '', time: '' },
				{ nr: 140, status: 0, date: '', time: '' },
				{ nr: 141, status: 0, date: '', time: '' },
				{ nr: 142, status: 0, date: '', time: '' },
				{ nr: 143, status: 0, date: '', time: '' },
				{ nr: 144, status: 0, date: '', time: '' },
				{ nr: 145, status: 0, date: '', time: '' },
				{ nr: 146, status: 0, date: '', time: '' },
				{ nr: 147, status: 0, date: '', time: '' },
				{ nr: 148, status: 0, date: '', time: '' },
				{ nr: 149, status: 0, date: '', time: '' },
				{ nr: 150, status: 0, date: '', time: '' },
				{ nr: 151, status: 0, date: '', time: '' },
				{ nr: 152, status: 0, date: '', time: '' }

			],
		},
		// basement B3
		{
		    nr: 2,
		    label: 'Basement B3',
		    min: 153,
		    max: 304,
		    stalls: [
				{ nr: 153, status: 0, date: '', time: '' },
				{ nr: 154, status: 0, date: '', time: '' },
				{ nr: 155, status: 0, date: '', time: '' },
				{ nr: 156, status: 0, date: '', time: '' },
				{ nr: 157, status: 0, date: '', time: '' },
				{ nr: 158, status: 0, date: '', time: '' },
				{ nr: 159, status: 0, date: '', time: '' },
				{ nr: 160, status: 0, date: '', time: '' },
				{ nr: 161, status: 0, date: '', time: '' },
				{ nr: 162, status: 0, date: '', time: '' },
				{ nr: 163, status: 0, date: '', time: '' },
				{ nr: 164, status: 0, date: '', time: '' },
				{ nr: 165, status: 0, date: '', time: '' },
				{ nr: 166, status: 0, date: '', time: '' },
				{ nr: 167, status: 0, date: '', time: '' },
				{ nr: 168, status: 0, date: '', time: '' },
				{ nr: 169, status: 0, date: '', time: '' },
				{ nr: 170, status: 0, date: '', time: '' },
				{ nr: 171, status: 0, date: '', time: '' },
				{ nr: 172, status: 0, date: '', time: '' },
				{ nr: 173, status: 0, date: '', time: '' },
				{ nr: 174, status: 0, date: '', time: '' },
				{ nr: 175, status: 0, date: '', time: '' },
				{ nr: 176, status: 0, date: '', time: '' },
				{ nr: 177, status: 0, date: '', time: '' },
				{ nr: 178, status: 0, date: '', time: '' },
				{ nr: 179, status: 0, date: '', time: '' },
				{ nr: 180, status: 0, date: '', time: '' },
				{ nr: 181, status: 0, date: '', time: '' },
				{ nr: 182, status: 0, date: '', time: '' },
				{ nr: 183, status: 0, date: '', time: '' },
				{ nr: 184, status: 0, date: '', time: '' },
				{ nr: 185, status: 0, date: '', time: '' },
				{ nr: 186, status: 0, date: '', time: '' },
				{ nr: 187, status: 0, date: '', time: '' },
				{ nr: 188, status: 0, date: '', time: '' },
				{ nr: 189, status: 0, date: '', time: '' },
				{ nr: 190, status: 0, date: '', time: '' },
				{ nr: 191, status: 0, date: '', time: '' },
				{ nr: 192, status: 0, date: '', time: '' },
				{ nr: 193, status: 0, date: '', time: '' },
				{ nr: 194, status: 0, date: '', time: '' },
				{ nr: 195, status: 0, date: '', time: '' },
				{ nr: 196, status: 0, date: '', time: '' },
				{ nr: 197, status: 0, date: '', time: '' },
				{ nr: 198, status: 0, date: '', time: '' },
				{ nr: 199, status: 0, date: '', time: '' },
				{ nr: 200, status: 0, date: '', time: '' },
				{ nr: 201, status: 0, date: '', time: '' },
				{ nr: 202, status: 0, date: '', time: '' },
				{ nr: 203, status: 0, date: '', time: '' },
				{ nr: 204, status: 0, date: '', time: '' },
				{ nr: 205, status: 0, date: '', time: '' },
				{ nr: 206, status: 0, date: '', time: '' },
				{ nr: 207, status: 0, date: '', time: '' },
				{ nr: 208, status: 0, date: '', time: '' },
				{ nr: 209, status: 0, date: '', time: '' },
				{ nr: 210, status: 0, date: '', time: '' },
				{ nr: 211, status: 0, date: '', time: '' },
				{ nr: 212, status: 0, date: '', time: '' },
				{ nr: 213, status: 0, date: '', time: '' },
				{ nr: 214, status: 0, date: '', time: '' },
				{ nr: 215, status: 0, date: '', time: '' },
				{ nr: 216, status: 0, date: '', time: '' },
				{ nr: 217, status: 0, date: '', time: '' },
				{ nr: 218, status: 0, date: '', time: '' },
				{ nr: 219, status: 0, date: '', time: '' },
				{ nr: 220, status: 0, date: '', time: '' },
				{ nr: 221, status: 0, date: '', time: '' },
				{ nr: 222, status: 0, date: '', time: '' },
				{ nr: 223, status: 0, date: '', time: '' },
				{ nr: 224, status: 0, date: '', time: '' },
				{ nr: 225, status: 0, date: '', time: '' },
				{ nr: 226, status: 0, date: '', time: '' },
				{ nr: 227, status: 0, date: '', time: '' },
				{ nr: 228, status: 0, date: '', time: '' },
				{ nr: 229, status: 0, date: '', time: '' },
				{ nr: 230, status: 0, date: '', time: '' },
				{ nr: 231, status: 0, date: '', time: '' },
				{ nr: 232, status: 0, date: '', time: '' },
				{ nr: 233, status: 0, date: '', time: '' },
				{ nr: 234, status: 0, date: '', time: '' },
				{ nr: 235, status: 0, date: '', time: '' },
				{ nr: 236, status: 0, date: '', time: '' },
				{ nr: 237, status: 0, date: '', time: '' },
				{ nr: 238, status: 0, date: '', time: '' },
				{ nr: 239, status: 0, date: '', time: '' },
				{ nr: 240, status: 0, date: '', time: '' },
				{ nr: 241, status: 0, date: '', time: '' },
				{ nr: 242, status: 0, date: '', time: '' },
				{ nr: 243, status: 0, date: '', time: '' },
				{ nr: 244, status: 0, date: '', time: '' },
				{ nr: 245, status: 0, date: '', time: '' },
				{ nr: 246, status: 0, date: '', time: '' },
				{ nr: 247, status: 0, date: '', time: '' },
				{ nr: 248, status: 0, date: '', time: '' },
				{ nr: 249, status: 0, date: '', time: '' },
				{ nr: 250, status: 0, date: '', time: '' },
				{ nr: 251, status: 0, date: '', time: '' },
				{ nr: 252, status: 0, date: '', time: '' },
				{ nr: 253, status: 0, date: '', time: '' },
				{ nr: 254, status: 0, date: '', time: '' },
				{ nr: 255, status: 0, date: '', time: '' },
				{ nr: 256, status: 0, date: '', time: '' },
				{ nr: 257, status: 0, date: '', time: '' },
				{ nr: 258, status: 0, date: '', time: '' },
				{ nr: 259, status: 0, date: '', time: '' },
				{ nr: 260, status: 0, date: '', time: '' },
				{ nr: 261, status: 0, date: '', time: '' },
				{ nr: 262, status: 0, date: '', time: '' },
				{ nr: 263, status: 0, date: '', time: '' },
				{ nr: 264, status: 0, date: '', time: '' },
				{ nr: 265, status: 0, date: '', time: '' },
				{ nr: 266, status: 0, date: '', time: '' },
				{ nr: 267, status: 0, date: '', time: '' },
				{ nr: 268, status: 0, date: '', time: '' },
				{ nr: 269, status: 0, date: '', time: '' },
				{ nr: 270, status: 0, date: '', time: '' },
				{ nr: 271, status: 0, date: '', time: '' },
				{ nr: 272, status: 0, date: '', time: '' },
				{ nr: 273, status: 0, date: '', time: '' },
				{ nr: 274, status: 0, date: '', time: '' },
				{ nr: 275, status: 0, date: '', time: '' },
				{ nr: 276, status: 0, date: '', time: '' },
				{ nr: 277, status: 0, date: '', time: '' },
				{ nr: 278, status: 0, date: '', time: '' },
				{ nr: 279, status: 0, date: '', time: '' },
				{ nr: 280, status: 0, date: '', time: '' },
				{ nr: 281, status: 0, date: '', time: '' },
				{ nr: 282, status: 0, date: '', time: '' },
				{ nr: 283, status: 0, date: '', time: '' },
				{ nr: 284, status: 0, date: '', time: '' },
				{ nr: 285, status: 0, date: '', time: '' },
				{ nr: 286, status: 0, date: '', time: '' },
				{ nr: 287, status: 0, date: '', time: '' },
				{ nr: 288, status: 0, date: '', time: '' },
				{ nr: 289, status: 0, date: '', time: '' },
				{ nr: 290, status: 0, date: '', time: '' },
				{ nr: 291, status: 0, date: '', time: '' },
				{ nr: 292, status: 0, date: '', time: '' },
				{ nr: 293, status: 0, date: '', time: '' },
				{ nr: 294, status: 0, date: '', time: '' },
				{ nr: 295, status: 0, date: '', time: '' },
				{ nr: 296, status: 0, date: '', time: '' },
				{ nr: 297, status: 0, date: '', time: '' },
				{ nr: 298, status: 0, date: '', time: '' },
				{ nr: 299, status: 0, date: '', time: '' },
				{ nr: 300, status: 0, date: '', time: '' },
				{ nr: 301, status: 0, date: '', time: '' },
				{ nr: 302, status: 0, date: '', time: '' },
				{ nr: 303, status: 0, date: '', time: '' },
				{ nr: 304, status: 0, date: '', time: '' }

			],
		},
		// basement B4
		{
		    nr: 3,
		    label: 'Basement B4',
		    min: 305,
		    max: 456,
		    stalls: [
				{ nr: 305, status: 0, date: '', time: '' },
				{ nr: 306, status: 0, date: '', time: '' },
				{ nr: 307, status: 0, date: '', time: '' },
				{ nr: 308, status: 0, date: '', time: '' },
				{ nr: 309, status: 0, date: '', time: '' },
				{ nr: 310, status: 0, date: '', time: '' },
				{ nr: 311, status: 0, date: '', time: '' },
				{ nr: 312, status: 0, date: '', time: '' },
				{ nr: 313, status: 0, date: '', time: '' },
				{ nr: 314, status: 0, date: '', time: '' },
				{ nr: 315, status: 0, date: '', time: '' },
				{ nr: 316, status: 0, date: '', time: '' },
				{ nr: 317, status: 0, date: '', time: '' },
				{ nr: 318, status: 0, date: '', time: '' },
				{ nr: 319, status: 0, date: '', time: '' },
				{ nr: 320, status: 0, date: '', time: '' },
				{ nr: 321, status: 0, date: '', time: '' },
				{ nr: 322, status: 0, date: '', time: '' },
				{ nr: 323, status: 0, date: '', time: '' },
				{ nr: 324, status: 0, date: '', time: '' },
				{ nr: 325, status: 0, date: '', time: '' },
				{ nr: 326, status: 0, date: '', time: '' },
				{ nr: 327, status: 0, date: '', time: '' },
				{ nr: 328, status: 0, date: '', time: '' },
				{ nr: 329, status: 0, date: '', time: '' },
				{ nr: 330, status: 0, date: '', time: '' },
				{ nr: 331, status: 0, date: '', time: '' },
				{ nr: 332, status: 0, date: '', time: '' },
				{ nr: 333, status: 0, date: '', time: '' },
				{ nr: 334, status: 0, date: '', time: '' },
				{ nr: 335, status: 0, date: '', time: '' },
				{ nr: 336, status: 0, date: '', time: '' },
				{ nr: 337, status: 0, date: '', time: '' },
				{ nr: 338, status: 0, date: '', time: '' },
				{ nr: 339, status: 0, date: '', time: '' },
				{ nr: 340, status: 0, date: '', time: '' },
				{ nr: 341, status: 0, date: '', time: '' },
				{ nr: 342, status: 0, date: '', time: '' },
				{ nr: 343, status: 0, date: '', time: '' },
				{ nr: 344, status: 0, date: '', time: '' },
				{ nr: 345, status: 0, date: '', time: '' },
				{ nr: 346, status: 0, date: '', time: '' },
				{ nr: 347, status: 0, date: '', time: '' },
				{ nr: 348, status: 0, date: '', time: '' },
				{ nr: 349, status: 0, date: '', time: '' },
				{ nr: 350, status: 0, date: '', time: '' },
				{ nr: 351, status: 0, date: '', time: '' },
				{ nr: 352, status: 0, date: '', time: '' },
				{ nr: 353, status: 0, date: '', time: '' },
				{ nr: 354, status: 0, date: '', time: '' },
				{ nr: 355, status: 0, date: '', time: '' },
				{ nr: 356, status: 0, date: '', time: '' },
				{ nr: 357, status: 0, date: '', time: '' },
				{ nr: 358, status: 0, date: '', time: '' },
				{ nr: 359, status: 0, date: '', time: '' },
				{ nr: 360, status: 0, date: '', time: '' },
				{ nr: 361, status: 0, date: '', time: '' },
				{ nr: 362, status: 0, date: '', time: '' },
				{ nr: 363, status: 0, date: '', time: '' },
				{ nr: 364, status: 0, date: '', time: '' },
				{ nr: 365, status: 0, date: '', time: '' },
				{ nr: 366, status: 0, date: '', time: '' },
				{ nr: 367, status: 0, date: '', time: '' },
				{ nr: 368, status: 0, date: '', time: '' },
				{ nr: 369, status: 0, date: '', time: '' },
				{ nr: 370, status: 0, date: '', time: '' },
				{ nr: 371, status: 0, date: '', time: '' },
				{ nr: 372, status: 0, date: '', time: '' },
				{ nr: 373, status: 0, date: '', time: '' },
				{ nr: 374, status: 0, date: '', time: '' },
				{ nr: 375, status: 0, date: '', time: '' },
				{ nr: 376, status: 0, date: '', time: '' },
				{ nr: 377, status: 0, date: '', time: '' },
				{ nr: 378, status: 0, date: '', time: '' },
				{ nr: 379, status: 0, date: '', time: '' },
				{ nr: 380, status: 0, date: '', time: '' },
				{ nr: 381, status: 0, date: '', time: '' },
				{ nr: 382, status: 0, date: '', time: '' },
				{ nr: 383, status: 0, date: '', time: '' },
				{ nr: 384, status: 0, date: '', time: '' },
				{ nr: 385, status: 0, date: '', time: '' },
				{ nr: 386, status: 0, date: '', time: '' },
				{ nr: 387, status: 0, date: '', time: '' },
				{ nr: 388, status: 0, date: '', time: '' },
				{ nr: 389, status: 0, date: '', time: '' },
				{ nr: 390, status: 0, date: '', time: '' },
				{ nr: 391, status: 0, date: '', time: '' },
				{ nr: 392, status: 0, date: '', time: '' },
				{ nr: 393, status: 0, date: '', time: '' },
				{ nr: 394, status: 0, date: '', time: '' },
				{ nr: 395, status: 0, date: '', time: '' },
				{ nr: 396, status: 0, date: '', time: '' },
				{ nr: 397, status: 0, date: '', time: '' },
				{ nr: 398, status: 0, date: '', time: '' },
				{ nr: 399, status: 0, date: '', time: '' },
				{ nr: 400, status: 0, date: '', time: '' },
				{ nr: 401, status: 0, date: '', time: '' },
				{ nr: 402, status: 0, date: '', time: '' },
				{ nr: 403, status: 0, date: '', time: '' },
				{ nr: 404, status: 0, date: '', time: '' },
				{ nr: 405, status: 0, date: '', time: '' },
				{ nr: 406, status: 0, date: '', time: '' },
				{ nr: 407, status: 0, date: '', time: '' },
				{ nr: 408, status: 0, date: '', time: '' },
				{ nr: 409, status: 0, date: '', time: '' },
				{ nr: 410, status: 0, date: '', time: '' },
				{ nr: 411, status: 0, date: '', time: '' },
				{ nr: 412, status: 0, date: '', time: '' },
				{ nr: 413, status: 0, date: '', time: '' },
				{ nr: 414, status: 0, date: '', time: '' },
				{ nr: 415, status: 0, date: '', time: '' },
				{ nr: 416, status: 0, date: '', time: '' },
				{ nr: 417, status: 0, date: '', time: '' },
				{ nr: 418, status: 0, date: '', time: '' },
				{ nr: 419, status: 0, date: '', time: '' },
				{ nr: 420, status: 0, date: '', time: '' },
				{ nr: 421, status: 0, date: '', time: '' },
				{ nr: 422, status: 0, date: '', time: '' },
				{ nr: 423, status: 0, date: '', time: '' },
				{ nr: 424, status: 0, date: '', time: '' },
				{ nr: 425, status: 0, date: '', time: '' },
				{ nr: 426, status: 0, date: '', time: '' },
				{ nr: 427, status: 0, date: '', time: '' },
				{ nr: 428, status: 0, date: '', time: '' },
				{ nr: 429, status: 0, date: '', time: '' },
				{ nr: 430, status: 0, date: '', time: '' },
				{ nr: 431, status: 0, date: '', time: '' },
				{ nr: 432, status: 0, date: '', time: '' },
				{ nr: 433, status: 0, date: '', time: '' },
				{ nr: 434, status: 0, date: '', time: '' },
				{ nr: 435, status: 0, date: '', time: '' },
				{ nr: 436, status: 0, date: '', time: '' },
				{ nr: 437, status: 0, date: '', time: '' },
				{ nr: 438, status: 0, date: '', time: '' },
				{ nr: 439, status: 0, date: '', time: '' },
				{ nr: 440, status: 0, date: '', time: '' },
				{ nr: 441, status: 0, date: '', time: '' },
				{ nr: 442, status: 0, date: '', time: '' },
				{ nr: 443, status: 0, date: '', time: '' },
				{ nr: 444, status: 0, date: '', time: '' },
				{ nr: 445, status: 0, date: '', time: '' },
				{ nr: 446, status: 0, date: '', time: '' },
				{ nr: 447, status: 0, date: '', time: '' },
				{ nr: 448, status: 0, date: '', time: '' },
				{ nr: 449, status: 0, date: '', time: '' },
				{ nr: 450, status: 0, date: '', time: '' },
				{ nr: 451, status: 0, date: '', time: '' },
				{ nr: 452, status: 0, date: '', time: '' },
				{ nr: 453, status: 0, date: '', time: '' },
				{ nr: 454, status: 0, date: '', time: '' },
				{ nr: 455, status: 0, date: '', time: '' },
				{ nr: 456, status: 0, date: '', time: '' }

			],
		},
		// basement B5
		{
		    nr: 4,
		    label: 'Basement B4',
		    min: 457,
		    max: 608,
		    stalls: [
				{ nr: 457, status: 0, date: '', time: '' },
				{ nr: 458, status: 0, date: '', time: '' },
				{ nr: 459, status: 0, date: '', time: '' },
				{ nr: 460, status: 0, date: '', time: '' },
				{ nr: 461, status: 0, date: '', time: '' },
				{ nr: 462, status: 0, date: '', time: '' },
				{ nr: 463, status: 0, date: '', time: '' },
				{ nr: 464, status: 0, date: '', time: '' },
				{ nr: 465, status: 0, date: '', time: '' },
				{ nr: 466, status: 0, date: '', time: '' },
				{ nr: 467, status: 0, date: '', time: '' },
				{ nr: 468, status: 0, date: '', time: '' },
				{ nr: 469, status: 0, date: '', time: '' },
				{ nr: 470, status: 0, date: '', time: '' },
				{ nr: 471, status: 0, date: '', time: '' },
				{ nr: 472, status: 0, date: '', time: '' },
				{ nr: 473, status: 0, date: '', time: '' },
				{ nr: 474, status: 0, date: '', time: '' },
				{ nr: 475, status: 0, date: '', time: '' },
				{ nr: 476, status: 0, date: '', time: '' },
				{ nr: 477, status: 0, date: '', time: '' },
				{ nr: 478, status: 0, date: '', time: '' },
				{ nr: 479, status: 0, date: '', time: '' },
				{ nr: 480, status: 0, date: '', time: '' },
				{ nr: 481, status: 0, date: '', time: '' },
				{ nr: 482, status: 0, date: '', time: '' },
				{ nr: 483, status: 0, date: '', time: '' },
				{ nr: 484, status: 0, date: '', time: '' },
				{ nr: 485, status: 0, date: '', time: '' },
				{ nr: 486, status: 0, date: '', time: '' },
				{ nr: 487, status: 0, date: '', time: '' },
				{ nr: 488, status: 0, date: '', time: '' },
				{ nr: 489, status: 0, date: '', time: '' },
				{ nr: 490, status: 0, date: '', time: '' },
				{ nr: 491, status: 0, date: '', time: '' },
				{ nr: 492, status: 0, date: '', time: '' },
				{ nr: 493, status: 0, date: '', time: '' },
				{ nr: 494, status: 0, date: '', time: '' },
				{ nr: 495, status: 0, date: '', time: '' },
				{ nr: 496, status: 0, date: '', time: '' },
				{ nr: 497, status: 0, date: '', time: '' },
				{ nr: 498, status: 0, date: '', time: '' },
				{ nr: 499, status: 0, date: '', time: '' },
				{ nr: 500, status: 0, date: '', time: '' },
				{ nr: 501, status: 0, date: '', time: '' },
				{ nr: 502, status: 0, date: '', time: '' },
				{ nr: 503, status: 0, date: '', time: '' },
				{ nr: 504, status: 0, date: '', time: '' },
				{ nr: 505, status: 0, date: '', time: '' },
				{ nr: 506, status: 0, date: '', time: '' },
				{ nr: 507, status: 0, date: '', time: '' },
				{ nr: 508, status: 0, date: '', time: '' },
				{ nr: 509, status: 0, date: '', time: '' },
				{ nr: 510, status: 0, date: '', time: '' },
				{ nr: 511, status: 0, date: '', time: '' },
				{ nr: 512, status: 0, date: '', time: '' },
				{ nr: 513, status: 0, date: '', time: '' },
				{ nr: 514, status: 0, date: '', time: '' },
				{ nr: 515, status: 0, date: '', time: '' },
				{ nr: 516, status: 0, date: '', time: '' },
				{ nr: 517, status: 0, date: '', time: '' },
				{ nr: 518, status: 0, date: '', time: '' },
				{ nr: 519, status: 0, date: '', time: '' },
				{ nr: 520, status: 0, date: '', time: '' },
				{ nr: 521, status: 0, date: '', time: '' },
				{ nr: 522, status: 0, date: '', time: '' },
				{ nr: 523, status: 0, date: '', time: '' },
				{ nr: 524, status: 0, date: '', time: '' },
				{ nr: 525, status: 0, date: '', time: '' },
				{ nr: 526, status: 0, date: '', time: '' },
				{ nr: 527, status: 0, date: '', time: '' },
				{ nr: 528, status: 0, date: '', time: '' },
				{ nr: 529, status: 0, date: '', time: '' },
				{ nr: 530, status: 0, date: '', time: '' },
				{ nr: 531, status: 0, date: '', time: '' },
				{ nr: 532, status: 0, date: '', time: '' },
				{ nr: 533, status: 0, date: '', time: '' },
				{ nr: 534, status: 0, date: '', time: '' },
				{ nr: 535, status: 0, date: '', time: '' },
				{ nr: 536, status: 0, date: '', time: '' },
				{ nr: 537, status: 0, date: '', time: '' },
				{ nr: 538, status: 0, date: '', time: '' },
				{ nr: 539, status: 0, date: '', time: '' },
				{ nr: 540, status: 0, date: '', time: '' },
				{ nr: 541, status: 0, date: '', time: '' },
				{ nr: 542, status: 0, date: '', time: '' },
				{ nr: 543, status: 0, date: '', time: '' },
				{ nr: 544, status: 0, date: '', time: '' },
				{ nr: 545, status: 0, date: '', time: '' },
				{ nr: 546, status: 0, date: '', time: '' },
				{ nr: 547, status: 0, date: '', time: '' },
				{ nr: 548, status: 0, date: '', time: '' },
				{ nr: 549, status: 0, date: '', time: '' },
				{ nr: 550, status: 0, date: '', time: '' },
				{ nr: 551, status: 0, date: '', time: '' },
				{ nr: 552, status: 0, date: '', time: '' },
				{ nr: 553, status: 0, date: '', time: '' },
				{ nr: 554, status: 0, date: '', time: '' },
				{ nr: 555, status: 0, date: '', time: '' },
				{ nr: 556, status: 0, date: '', time: '' },
				{ nr: 557, status: 0, date: '', time: '' },
				{ nr: 558, status: 0, date: '', time: '' },
				{ nr: 559, status: 0, date: '', time: '' },
				{ nr: 560, status: 0, date: '', time: '' },
				{ nr: 561, status: 0, date: '', time: '' },
				{ nr: 562, status: 0, date: '', time: '' },
				{ nr: 563, status: 0, date: '', time: '' },
				{ nr: 564, status: 0, date: '', time: '' },
				{ nr: 565, status: 0, date: '', time: '' },
				{ nr: 566, status: 0, date: '', time: '' },
				{ nr: 567, status: 0, date: '', time: '' },
				{ nr: 568, status: 0, date: '', time: '' },
				{ nr: 569, status: 0, date: '', time: '' },
				{ nr: 570, status: 0, date: '', time: '' },
				{ nr: 571, status: 0, date: '', time: '' },
				{ nr: 572, status: 0, date: '', time: '' },
				{ nr: 573, status: 0, date: '', time: '' },
				{ nr: 574, status: 0, date: '', time: '' },
				{ nr: 575, status: 0, date: '', time: '' },
				{ nr: 576, status: 0, date: '', time: '' },
				{ nr: 577, status: 0, date: '', time: '' },
				{ nr: 578, status: 0, date: '', time: '' },
				{ nr: 579, status: 0, date: '', time: '' },
				{ nr: 580, status: 0, date: '', time: '' },
				{ nr: 581, status: 0, date: '', time: '' },
				{ nr: 582, status: 0, date: '', time: '' },
				{ nr: 583, status: 0, date: '', time: '' },
				{ nr: 584, status: 0, date: '', time: '' },
				{ nr: 585, status: 0, date: '', time: '' },
				{ nr: 586, status: 0, date: '', time: '' },
				{ nr: 587, status: 0, date: '', time: '' },
				{ nr: 588, status: 0, date: '', time: '' },
				{ nr: 589, status: 0, date: '', time: '' },
				{ nr: 590, status: 0, date: '', time: '' },
				{ nr: 591, status: 0, date: '', time: '' },
				{ nr: 592, status: 0, date: '', time: '' },
				{ nr: 593, status: 0, date: '', time: '' },
				{ nr: 594, status: 0, date: '', time: '' },
				{ nr: 595, status: 0, date: '', time: '' },
				{ nr: 596, status: 0, date: '', time: '' },
				{ nr: 597, status: 0, date: '', time: '' },
				{ nr: 598, status: 0, date: '', time: '' },
				{ nr: 599, status: 0, date: '', time: '' },
				{ nr: 600, status: 0, date: '', time: '' },
				{ nr: 601, status: 0, date: '', time: '' },
				{ nr: 602, status: 0, date: '', time: '' },
				{ nr: 603, status: 0, date: '', time: '' },
				{ nr: 604, status: 0, date: '', time: '' },
				{ nr: 605, status: 0, date: '', time: '' },
				{ nr: 606, status: 0, date: '', time: '' },
				{ nr: 607, status: 0, date: '', time: '' },
				{ nr: 608, status: 0, date: '', time: '' }

			],
		},
		// basement B6
		{
		    nr: 5,
		    label: 'Basement B6',
		    min: 609,
		    max: 760,
		    stalls: [
				{ nr: 609, status: 0, date: '', time: '' },
				{ nr: 610, status: 0, date: '', time: '' },
				{ nr: 611, status: 0, date: '', time: '' },
				{ nr: 612, status: 0, date: '', time: '' },
				{ nr: 613, status: 0, date: '', time: '' },
				{ nr: 614, status: 0, date: '', time: '' },
				{ nr: 615, status: 0, date: '', time: '' },
				{ nr: 616, status: 0, date: '', time: '' },
				{ nr: 617, status: 0, date: '', time: '' },
				{ nr: 618, status: 0, date: '', time: '' },
				{ nr: 619, status: 0, date: '', time: '' },
				{ nr: 620, status: 0, date: '', time: '' },
				{ nr: 621, status: 0, date: '', time: '' },
				{ nr: 622, status: 0, date: '', time: '' },
				{ nr: 623, status: 0, date: '', time: '' },
				{ nr: 624, status: 0, date: '', time: '' },
				{ nr: 625, status: 0, date: '', time: '' },
				{ nr: 626, status: 0, date: '', time: '' },
				{ nr: 627, status: 0, date: '', time: '' },
				{ nr: 628, status: 0, date: '', time: '' },
				{ nr: 629, status: 0, date: '', time: '' },
				{ nr: 630, status: 0, date: '', time: '' },
				{ nr: 631, status: 0, date: '', time: '' },
				{ nr: 632, status: 0, date: '', time: '' },
				{ nr: 633, status: 0, date: '', time: '' },
				{ nr: 634, status: 0, date: '', time: '' },
				{ nr: 635, status: 0, date: '', time: '' },
				{ nr: 636, status: 0, date: '', time: '' },
				{ nr: 637, status: 0, date: '', time: '' },
				{ nr: 638, status: 0, date: '', time: '' },
				{ nr: 639, status: 0, date: '', time: '' },
				{ nr: 640, status: 0, date: '', time: '' },
				{ nr: 641, status: 0, date: '', time: '' },
				{ nr: 642, status: 0, date: '', time: '' },
				{ nr: 643, status: 0, date: '', time: '' },
				{ nr: 644, status: 0, date: '', time: '' },
				{ nr: 645, status: 0, date: '', time: '' },
				{ nr: 646, status: 0, date: '', time: '' },
				{ nr: 647, status: 0, date: '', time: '' },
				{ nr: 648, status: 0, date: '', time: '' },
				{ nr: 649, status: 0, date: '', time: '' },
				{ nr: 650, status: 0, date: '', time: '' },
				{ nr: 651, status: 0, date: '', time: '' },
				{ nr: 652, status: 0, date: '', time: '' },
				{ nr: 653, status: 0, date: '', time: '' },
				{ nr: 654, status: 0, date: '', time: '' },
				{ nr: 655, status: 0, date: '', time: '' },
				{ nr: 656, status: 0, date: '', time: '' },
				{ nr: 657, status: 0, date: '', time: '' },
				{ nr: 658, status: 0, date: '', time: '' },
				{ nr: 659, status: 0, date: '', time: '' },
				{ nr: 660, status: 0, date: '', time: '' },
				{ nr: 661, status: 0, date: '', time: '' },
				{ nr: 662, status: 0, date: '', time: '' },
				{ nr: 663, status: 0, date: '', time: '' },
				{ nr: 664, status: 0, date: '', time: '' },
				{ nr: 665, status: 0, date: '', time: '' },
				{ nr: 666, status: 0, date: '', time: '' },
				{ nr: 667, status: 0, date: '', time: '' },
				{ nr: 668, status: 0, date: '', time: '' },
				{ nr: 669, status: 0, date: '', time: '' },
				{ nr: 670, status: 0, date: '', time: '' },
				{ nr: 671, status: 0, date: '', time: '' },
				{ nr: 672, status: 0, date: '', time: '' },
				{ nr: 673, status: 0, date: '', time: '' },
				{ nr: 674, status: 0, date: '', time: '' },
				{ nr: 675, status: 0, date: '', time: '' },
				{ nr: 676, status: 0, date: '', time: '' },
				{ nr: 677, status: 0, date: '', time: '' },
				{ nr: 678, status: 0, date: '', time: '' },
				{ nr: 679, status: 0, date: '', time: '' },
				{ nr: 680, status: 0, date: '', time: '' },
				{ nr: 681, status: 0, date: '', time: '' },
				{ nr: 682, status: 0, date: '', time: '' },
				{ nr: 683, status: 0, date: '', time: '' },
				{ nr: 684, status: 0, date: '', time: '' },
				{ nr: 685, status: 0, date: '', time: '' },
				{ nr: 686, status: 0, date: '', time: '' },
				{ nr: 687, status: 0, date: '', time: '' },
				{ nr: 688, status: 0, date: '', time: '' },
				{ nr: 689, status: 0, date: '', time: '' },
				{ nr: 690, status: 0, date: '', time: '' },
				{ nr: 691, status: 0, date: '', time: '' },
				{ nr: 692, status: 0, date: '', time: '' },
				{ nr: 693, status: 0, date: '', time: '' },
				{ nr: 694, status: 0, date: '', time: '' },
				{ nr: 695, status: 0, date: '', time: '' },
				{ nr: 696, status: 0, date: '', time: '' },
				{ nr: 697, status: 0, date: '', time: '' },
				{ nr: 698, status: 0, date: '', time: '' },
				{ nr: 699, status: 0, date: '', time: '' },
				{ nr: 700, status: 0, date: '', time: '' },
				{ nr: 701, status: 0, date: '', time: '' },
				{ nr: 702, status: 0, date: '', time: '' },
				{ nr: 703, status: 0, date: '', time: '' },
				{ nr: 704, status: 0, date: '', time: '' },
				{ nr: 705, status: 0, date: '', time: '' },
				{ nr: 706, status: 0, date: '', time: '' },
				{ nr: 707, status: 0, date: '', time: '' },
				{ nr: 708, status: 0, date: '', time: '' },
				{ nr: 709, status: 0, date: '', time: '' },
				{ nr: 710, status: 0, date: '', time: '' },
				{ nr: 711, status: 0, date: '', time: '' },
				{ nr: 712, status: 0, date: '', time: '' },
				{ nr: 713, status: 0, date: '', time: '' },
				{ nr: 714, status: 0, date: '', time: '' },
				{ nr: 715, status: 0, date: '', time: '' },
				{ nr: 716, status: 0, date: '', time: '' },
				{ nr: 717, status: 0, date: '', time: '' },
				{ nr: 718, status: 0, date: '', time: '' },
				{ nr: 719, status: 0, date: '', time: '' },
				{ nr: 720, status: 0, date: '', time: '' },
				{ nr: 721, status: 0, date: '', time: '' },
				{ nr: 722, status: 0, date: '', time: '' },
				{ nr: 723, status: 0, date: '', time: '' },
				{ nr: 724, status: 0, date: '', time: '' },
				{ nr: 725, status: 0, date: '', time: '' },
				{ nr: 726, status: 0, date: '', time: '' },
				{ nr: 727, status: 0, date: '', time: '' },
				{ nr: 728, status: 0, date: '', time: '' },
				{ nr: 729, status: 0, date: '', time: '' },
				{ nr: 730, status: 0, date: '', time: '' },
				{ nr: 731, status: 0, date: '', time: '' },
				{ nr: 732, status: 0, date: '', time: '' },
				{ nr: 733, status: 0, date: '', time: '' },
				{ nr: 734, status: 0, date: '', time: '' },
				{ nr: 735, status: 0, date: '', time: '' },
				{ nr: 736, status: 0, date: '', time: '' },
				{ nr: 737, status: 0, date: '', time: '' },
				{ nr: 738, status: 0, date: '', time: '' },
				{ nr: 739, status: 0, date: '', time: '' },
				{ nr: 740, status: 0, date: '', time: '' },
				{ nr: 741, status: 0, date: '', time: '' },
				{ nr: 742, status: 0, date: '', time: '' },
				{ nr: 743, status: 0, date: '', time: '' },
				{ nr: 744, status: 0, date: '', time: '' },
				{ nr: 745, status: 0, date: '', time: '' },
				{ nr: 746, status: 0, date: '', time: '' },
				{ nr: 747, status: 0, date: '', time: '' },
				{ nr: 748, status: 0, date: '', time: '' },
				{ nr: 749, status: 0, date: '', time: '' },
				{ nr: 750, status: 0, date: '', time: '' },
				{ nr: 751, status: 0, date: '', time: '' },
				{ nr: 752, status: 0, date: '', time: '' },
				{ nr: 753, status: 0, date: '', time: '' },
				{ nr: 754, status: 0, date: '', time: '' },
				{ nr: 755, status: 0, date: '', time: '' },
				{ nr: 756, status: 0, date: '', time: '' },
				{ nr: 757, status: 0, date: '', time: '' },
				{ nr: 758, status: 0, date: '', time: '' },
				{ nr: 759, status: 0, date: '', time: '' },
				{ nr: 760, status: 0, date: '', time: '' }

			],
		},
		// basement B7
		{
		    nr: 6,
		    label: 'Basement B7',
		    min: 761,
		    max: 912,
		    stalls: [
				{ nr: 761, status: 0, date: '', time: '' },
				{ nr: 762, status: 0, date: '', time: '' },
				{ nr: 763, status: 0, date: '', time: '' },
				{ nr: 764, status: 0, date: '', time: '' },
				{ nr: 765, status: 0, date: '', time: '' },
				{ nr: 766, status: 0, date: '', time: '' },
				{ nr: 767, status: 0, date: '', time: '' },
				{ nr: 768, status: 0, date: '', time: '' },
				{ nr: 769, status: 0, date: '', time: '' },
				{ nr: 770, status: 0, date: '', time: '' },
				{ nr: 771, status: 0, date: '', time: '' },
				{ nr: 772, status: 0, date: '', time: '' },
				{ nr: 773, status: 0, date: '', time: '' },
				{ nr: 774, status: 0, date: '', time: '' },
				{ nr: 775, status: 0, date: '', time: '' },
				{ nr: 776, status: 0, date: '', time: '' },
				{ nr: 777, status: 0, date: '', time: '' },
				{ nr: 778, status: 0, date: '', time: '' },
				{ nr: 779, status: 0, date: '', time: '' },
				{ nr: 780, status: 0, date: '', time: '' },
				{ nr: 781, status: 0, date: '', time: '' },
				{ nr: 782, status: 0, date: '', time: '' },
				{ nr: 783, status: 0, date: '', time: '' },
				{ nr: 784, status: 0, date: '', time: '' },
				{ nr: 785, status: 0, date: '', time: '' },
				{ nr: 786, status: 0, date: '', time: '' },
				{ nr: 787, status: 0, date: '', time: '' },
				{ nr: 788, status: 0, date: '', time: '' },
				{ nr: 789, status: 0, date: '', time: '' },
				{ nr: 790, status: 0, date: '', time: '' },
				{ nr: 791, status: 0, date: '', time: '' },
				{ nr: 792, status: 0, date: '', time: '' },
				{ nr: 793, status: 0, date: '', time: '' },
				{ nr: 794, status: 0, date: '', time: '' },
				{ nr: 795, status: 0, date: '', time: '' },
				{ nr: 796, status: 0, date: '', time: '' },
				{ nr: 797, status: 0, date: '', time: '' },
				{ nr: 798, status: 0, date: '', time: '' },
				{ nr: 799, status: 0, date: '', time: '' },
				{ nr: 800, status: 0, date: '', time: '' },
				{ nr: 801, status: 0, date: '', time: '' },
				{ nr: 802, status: 0, date: '', time: '' },
				{ nr: 803, status: 0, date: '', time: '' },
				{ nr: 804, status: 0, date: '', time: '' },
				{ nr: 805, status: 0, date: '', time: '' },
				{ nr: 806, status: 0, date: '', time: '' },
				{ nr: 807, status: 0, date: '', time: '' },
				{ nr: 808, status: 0, date: '', time: '' },
				{ nr: 809, status: 0, date: '', time: '' },
				{ nr: 810, status: 0, date: '', time: '' },
				{ nr: 811, status: 0, date: '', time: '' },
				{ nr: 812, status: 0, date: '', time: '' },
				{ nr: 813, status: 0, date: '', time: '' },
				{ nr: 814, status: 0, date: '', time: '' },
				{ nr: 815, status: 0, date: '', time: '' },
				{ nr: 816, status: 0, date: '', time: '' },
				{ nr: 817, status: 0, date: '', time: '' },
				{ nr: 818, status: 0, date: '', time: '' },
				{ nr: 819, status: 0, date: '', time: '' },
				{ nr: 820, status: 0, date: '', time: '' },
				{ nr: 821, status: 0, date: '', time: '' },
				{ nr: 822, status: 0, date: '', time: '' },
				{ nr: 823, status: 0, date: '', time: '' },
				{ nr: 824, status: 0, date: '', time: '' },
				{ nr: 825, status: 0, date: '', time: '' },
				{ nr: 826, status: 0, date: '', time: '' },
				{ nr: 827, status: 0, date: '', time: '' },
				{ nr: 828, status: 0, date: '', time: '' },
				{ nr: 829, status: 0, date: '', time: '' },
				{ nr: 830, status: 0, date: '', time: '' },
				{ nr: 831, status: 0, date: '', time: '' },
				{ nr: 832, status: 0, date: '', time: '' },
				{ nr: 833, status: 0, date: '', time: '' },
				{ nr: 834, status: 0, date: '', time: '' },
				{ nr: 835, status: 0, date: '', time: '' },
				{ nr: 836, status: 0, date: '', time: '' },
				{ nr: 837, status: 0, date: '', time: '' },
				{ nr: 838, status: 0, date: '', time: '' },
				{ nr: 839, status: 0, date: '', time: '' },
				{ nr: 840, status: 0, date: '', time: '' },
				{ nr: 841, status: 0, date: '', time: '' },
				{ nr: 842, status: 0, date: '', time: '' },
				{ nr: 843, status: 0, date: '', time: '' },
				{ nr: 844, status: 0, date: '', time: '' },
				{ nr: 845, status: 0, date: '', time: '' },
				{ nr: 846, status: 0, date: '', time: '' },
				{ nr: 847, status: 0, date: '', time: '' },
				{ nr: 848, status: 0, date: '', time: '' },
				{ nr: 849, status: 0, date: '', time: '' },
				{ nr: 850, status: 0, date: '', time: '' },
				{ nr: 851, status: 0, date: '', time: '' },
				{ nr: 852, status: 0, date: '', time: '' },
				{ nr: 853, status: 0, date: '', time: '' },
				{ nr: 854, status: 0, date: '', time: '' },
				{ nr: 855, status: 0, date: '', time: '' },
				{ nr: 856, status: 0, date: '', time: '' },
				{ nr: 857, status: 0, date: '', time: '' },
				{ nr: 858, status: 0, date: '', time: '' },
				{ nr: 859, status: 0, date: '', time: '' },
				{ nr: 860, status: 0, date: '', time: '' },
				{ nr: 861, status: 0, date: '', time: '' },
				{ nr: 862, status: 0, date: '', time: '' },
				{ nr: 863, status: 0, date: '', time: '' },
				{ nr: 864, status: 0, date: '', time: '' },
				{ nr: 865, status: 0, date: '', time: '' },
				{ nr: 866, status: 0, date: '', time: '' },
				{ nr: 867, status: 0, date: '', time: '' },
				{ nr: 868, status: 0, date: '', time: '' },
				{ nr: 869, status: 0, date: '', time: '' },
				{ nr: 870, status: 0, date: '', time: '' },
				{ nr: 871, status: 0, date: '', time: '' },
				{ nr: 872, status: 0, date: '', time: '' },
				{ nr: 873, status: 0, date: '', time: '' },
				{ nr: 874, status: 0, date: '', time: '' },
				{ nr: 875, status: 0, date: '', time: '' },
				{ nr: 876, status: 0, date: '', time: '' },
				{ nr: 877, status: 0, date: '', time: '' },
				{ nr: 878, status: 0, date: '', time: '' },
				{ nr: 879, status: 0, date: '', time: '' },
				{ nr: 880, status: 0, date: '', time: '' },
				{ nr: 881, status: 0, date: '', time: '' },
				{ nr: 882, status: 0, date: '', time: '' },
				{ nr: 883, status: 0, date: '', time: '' },
				{ nr: 884, status: 0, date: '', time: '' },
				{ nr: 885, status: 0, date: '', time: '' },
				{ nr: 886, status: 0, date: '', time: '' },
				{ nr: 887, status: 0, date: '', time: '' },
				{ nr: 888, status: 0, date: '', time: '' },
				{ nr: 889, status: 0, date: '', time: '' },
				{ nr: 890, status: 0, date: '', time: '' },
				{ nr: 891, status: 0, date: '', time: '' },
				{ nr: 892, status: 0, date: '', time: '' },
				{ nr: 893, status: 0, date: '', time: '' },
				{ nr: 894, status: 0, date: '', time: '' },
				{ nr: 895, status: 0, date: '', time: '' },
				{ nr: 896, status: 0, date: '', time: '' },
				{ nr: 897, status: 0, date: '', time: '' },
				{ nr: 898, status: 0, date: '', time: '' },
				{ nr: 899, status: 0, date: '', time: '' },
				{ nr: 900, status: 0, date: '', time: '' },
				{ nr: 901, status: 0, date: '', time: '' },
				{ nr: 902, status: 0, date: '', time: '' },
				{ nr: 903, status: 0, date: '', time: '' },
				{ nr: 904, status: 0, date: '', time: '' },
				{ nr: 905, status: 0, date: '', time: '' },
				{ nr: 906, status: 0, date: '', time: '' },
				{ nr: 907, status: 0, date: '', time: '' },
				{ nr: 908, status: 0, date: '', time: '' },
				{ nr: 909, status: 0, date: '', time: '' },
				{ nr: 910, status: 0, date: '', time: '' },
				{ nr: 911, status: 0, date: '', time: '' },
				{ nr: 912, status: 0, date: '', time: '' }

			],
		},

		    ],
	};
    //return data;
}
